# Generated by Django 5.0.4 on 2024-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('number_of_guest', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
