# Generated by Django 5.0.4 on 2024-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hotelbookings_delete_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(choices=[('DEL', 'Delhi - Indira Gandhi International Airport'), ('BOM', 'Mumbai - Chhatrapati Shivaji Maharaj International Airport'), ('BLR', 'Bangalore - Kempegowda International Airport'), ('HYD', 'Hyderabad - Rajiv Gandhi International Airport'), ('MAA', 'Chennai - Chennai International Airport'), ('CCU', 'Kolkata - Netaji Subhas Chandra Bose International Airport'), ('AMD', 'Ahmedabad - Sardar Vallabhbhai Patel International Airport'), ('COK', 'Kochi - Cochin International Airport'), ('GOI', 'Goa - Goa International Airport'), ('PNQ', 'Pune - Pune International Airport'), ('ATQ', 'Amritsar - Sri Guru Ram Dass Jee International Airport'), ('JAI', 'Jaipur - Jaipur International Airport'), ('TRV', 'Thiruvananthapuram - Trivandrum International Airport'), ('LKO', 'Lucknow - Chaudhary Charan Singh International Airport'), ('VGA', 'Vijayawada - Vijayawada International Airport'), ('PAT', 'Patna - Jay Prakash Narayan International Airport'), ('GAU', 'Guwahati - Lokpriya Gopinath Bordoloi International Airport'), ('SXR', 'Srinagar - Sheikh ul-Alam International Airport'), ('BBI', 'Bhubaneswar - Biju Patnaik International Airport')], max_length=3)),
                ('to_airport', models.CharField(choices=[('DEL', 'Delhi - Indira Gandhi International Airport'), ('BOM', 'Mumbai - Chhatrapati Shivaji Maharaj International Airport'), ('BLR', 'Bangalore - Kempegowda International Airport'), ('HYD', 'Hyderabad - Rajiv Gandhi International Airport'), ('MAA', 'Chennai - Chennai International Airport'), ('CCU', 'Kolkata - Netaji Subhas Chandra Bose International Airport'), ('AMD', 'Ahmedabad - Sardar Vallabhbhai Patel International Airport'), ('COK', 'Kochi - Cochin International Airport'), ('GOI', 'Goa - Goa International Airport'), ('PNQ', 'Pune - Pune International Airport'), ('ATQ', 'Amritsar - Sri Guru Ram Dass Jee International Airport'), ('JAI', 'Jaipur - Jaipur International Airport'), ('TRV', 'Thiruvananthapuram - Trivandrum International Airport'), ('LKO', 'Lucknow - Chaudhary Charan Singh International Airport'), ('VGA', 'Vijayawada - Vijayawada International Airport'), ('PAT', 'Patna - Jay Prakash Narayan International Airport'), ('GAU', 'Guwahati - Lokpriya Gopinath Bordoloi International Airport'), ('SXR', 'Srinagar - Sheikh ul-Alam International Airport'), ('BBI', 'Bhubaneswar - Biju Patnaik International Airport')], max_length=3)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('preferred_airlines', models.CharField(blank=True, choices=[('IndiGo', 'IndiGo'), ('AirIndia', 'AirIndia'), ('SpiceJet', 'SpiceJet')], max_length=50, null=True)),
                ('preferred_seating', models.CharField(blank=True, choices=[('Economy', 'Economy Class'), ('Business', 'Business Class'), ('First', 'First Class')], max_length=50, null=True)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField(blank=True, null=True)),
                ('infants', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], max_length=10)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='FlightBooking',
        ),
    ]
